server:
  port: 8020
  servlet:
    context-path: /beedo
spring:
  application:
    name: beedo
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: beedo
  jpa:
    database-platform: com.seagull.beedo.config.SQLiteDialect
    generate-ddl: true
    hibernate:
        ddl-auto: update
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://mariadb:3306/beedo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache

management:
  endpoints:
    server:
      port: 8890
    web:
      base-path: /actuator
      #开启所有端点
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  application: beedo
  author: huangguosheng
  email: 290529123@qq.com
