server:
  port: 8020
  servlet:
    context-path: /beedo
spring:
  application:
    name: beedo
  data:
    mongodb:
      host: 127.0.0.1
     # host: 60.205.207.196
      port: 27017
      database: beedo
  jpa:
    hibernate:
        ddl-auto: update
    database: mysql
    show-sql: true
  datasource:
    #url: jdbc:mysql://60.205.207.196:3306/beedo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/beedo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: asd123asd
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache
  security:
    user:
      name: hgsPiece
      password: asd123asd


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    server:
      port: 8889
    web:
      base-path: /actuator
      #开启所有端点
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  application: beedo
  author: huangguosheng
  email: 290529123@qq.com
