package com.seagull.beedo.dao;

import com.seagull.beedo.common.query.TaskNodeQuery;
import com.seagull.beedo.dao.domain.BeedoTaskNode;

import java.util.List;

public interface BeedoTaskNodeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beedo_task_node
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beedo_task_node
     *
     * @mbg.generated
     */
    int insert(BeedoTaskNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beedo_task_node
     *
     * @mbg.generated
     */
    int insertSelective(BeedoTaskNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beedo_task_node
     *
     * @mbg.generated
     */
    BeedoTaskNode selectByPrimaryKey(Integer id);

    List<BeedoTaskNode> selectByQuery(TaskNodeQuery query);

    List<BeedoTaskNode> selectByTaskParseUid(String taskParseUid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beedo_task_node
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BeedoTaskNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beedo_task_node
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BeedoTaskNode record);
}