package com.seagull.beedo.dao.domain;

import java.util.Date;

import team.seagull.common.base.common.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table beedo_task_parse
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BeedoTaskParse extends ToString {
    private static final long serialVersionUID = -144344831230025994L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.cron
     *
     * @mbg.generated
     */
    private String  cron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.dbname
     *
     * @mbg.generated
     */
    private String  dbname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.gmt_create
     *
     * @mbg.generated
     */
    private Date    gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.gmt_modified
     *
     * @mbg.generated
     */
    private Date    gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.memo
     *
     * @mbg.generated
     */
    private String  memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.name
     *
     * @mbg.generated
     */
    private String  name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.task_status
     *
     * @mbg.generated
     */
    private String  taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.thread_cool_size
     *
     * @mbg.generated
     */
    private Integer threadCoolSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.uid
     *
     * @mbg.generated
     */
    private String  uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.collection_name
     *
     * @mbg.generated
     */
    private String  collectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_parse.status
     *
     * @mbg.generated
     */
    private String  status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.id
     *
     * @return the value of beedo_task_parse.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.id
     *
     * @param id the value for beedo_task_parse.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.cron
     *
     * @return the value of beedo_task_parse.cron
     *
     * @mbg.generated
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.cron
     *
     * @param cron the value for beedo_task_parse.cron
     *
     * @mbg.generated
     */
    public void setCron(String cron) {
        this.cron = cron == null ? null : cron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.dbname
     *
     * @return the value of beedo_task_parse.dbname
     *
     * @mbg.generated
     */
    public String getDbname() {
        return dbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.dbname
     *
     * @param dbname the value for beedo_task_parse.dbname
     *
     * @mbg.generated
     */
    public void setDbname(String dbname) {
        this.dbname = dbname == null ? null : dbname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.gmt_create
     *
     * @return the value of beedo_task_parse.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.gmt_create
     *
     * @param gmtCreate the value for beedo_task_parse.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.gmt_modified
     *
     * @return the value of beedo_task_parse.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.gmt_modified
     *
     * @param gmtModified the value for beedo_task_parse.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.memo
     *
     * @return the value of beedo_task_parse.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.memo
     *
     * @param memo the value for beedo_task_parse.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.name
     *
     * @return the value of beedo_task_parse.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.name
     *
     * @param name the value for beedo_task_parse.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.task_status
     *
     * @return the value of beedo_task_parse.task_status
     *
     * @mbg.generated
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.task_status
     *
     * @param taskStatus the value for beedo_task_parse.task_status
     *
     * @mbg.generated
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.thread_cool_size
     *
     * @return the value of beedo_task_parse.thread_cool_size
     *
     * @mbg.generated
     */
    public Integer getThreadCoolSize() {
        return threadCoolSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.thread_cool_size
     *
     * @param threadCoolSize the value for beedo_task_parse.thread_cool_size
     *
     * @mbg.generated
     */
    public void setThreadCoolSize(Integer threadCoolSize) {
        this.threadCoolSize = threadCoolSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.uid
     *
     * @return the value of beedo_task_parse.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.uid
     *
     * @param uid the value for beedo_task_parse.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.collection_name
     *
     * @return the value of beedo_task_parse.collection_name
     *
     * @mbg.generated
     */
    public String getCollectionName() {
        return collectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.collection_name
     *
     * @param collectionName the value for beedo_task_parse.collection_name
     *
     * @mbg.generated
     */
    public void setCollectionName(String collectionName) {
        this.collectionName = collectionName == null ? null : collectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.level
     *
     * @return the value of beedo_task_parse.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.level
     *
     * @param level the value for beedo_task_parse.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_parse.status
     *
     * @return the value of beedo_task_parse.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_parse.status
     *
     * @param status the value for beedo_task_parse.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}