package com.seagull.beedo.dao.domain;

import team.seagull.common.base.common.ToString;

import java.util.Date;


/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table beedo_task_node
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BeedoTaskNode extends ToString {
    private static final long serialVersionUID = 4384060187977808690L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_node.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_node.document_id
     *
     * @mbg.generated
     */
    private Integer documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_node.element_info_map
     *
     * @mbg.generated
     */
    private String elementInfoMap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_node.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_node.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_node.task_parse_uid
     *
     * @mbg.generated
     */
    private String taskParseUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_task_node.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_node.id
     *
     * @return the value of beedo_task_node.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_node.id
     *
     * @param id the value for beedo_task_node.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_node.document_id
     *
     * @return the value of beedo_task_node.document_id
     *
     * @mbg.generated
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_node.document_id
     *
     * @param documentId the value for beedo_task_node.document_id
     *
     * @mbg.generated
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_node.element_info_map
     *
     * @return the value of beedo_task_node.element_info_map
     *
     * @mbg.generated
     */
    public String getElementInfoMap() {
        return elementInfoMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_node.element_info_map
     *
     * @param elementInfoMap the value for beedo_task_node.element_info_map
     *
     * @mbg.generated
     */
    public void setElementInfoMap(String elementInfoMap) {
        this.elementInfoMap = elementInfoMap == null ? null : elementInfoMap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_node.gmt_create
     *
     * @return the value of beedo_task_node.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_node.gmt_create
     *
     * @param gmtCreate the value for beedo_task_node.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_node.gmt_modified
     *
     * @return the value of beedo_task_node.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_node.gmt_modified
     *
     * @param gmtModified the value for beedo_task_node.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_node.task_parse_uid
     *
     * @return the value of beedo_task_node.task_parse_uid
     *
     * @mbg.generated
     */
    public String getTaskParseUid() {
        return taskParseUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_node.task_parse_uid
     *
     * @param taskParseUid the value for beedo_task_node.task_parse_uid
     *
     * @mbg.generated
     */
    public void setTaskParseUid(String taskParseUid) {
        this.taskParseUid = taskParseUid == null ? null : taskParseUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_task_node.status
     *
     * @return the value of beedo_task_node.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_task_node.status
     *
     * @param status the value for beedo_task_node.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}