package com.seagull.beedo.dao.domain;



import com.seagull.beedo.common.ToString;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table beedo_element
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BeedoElement extends ToString {
    private static final long serialVersionUID = -5496992255937600033L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_element.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_element.attr
     *
     * @mbg.generated
     */
    private String attr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_element.css_query
     *
     * @mbg.generated
     */
    private String cssQuery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_element.data_type
     *
     * @mbg.generated
     */
    private String dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_element.document_id
     *
     * @mbg.generated
     */
    private Integer documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_element.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_element.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_element.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_element.structure_type
     *
     * @mbg.generated
     */
    private String structureType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_element.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_element.id
     *
     * @return the value of beedo_element.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_element.id
     *
     * @param id the value for beedo_element.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_element.attr
     *
     * @return the value of beedo_element.attr
     *
     * @mbg.generated
     */
    public String getAttr() {
        return attr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_element.attr
     *
     * @param attr the value for beedo_element.attr
     *
     * @mbg.generated
     */
    public void setAttr(String attr) {
        this.attr = attr == null ? null : attr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_element.css_query
     *
     * @return the value of beedo_element.css_query
     *
     * @mbg.generated
     */
    public String getCssQuery() {
        return cssQuery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_element.css_query
     *
     * @param cssQuery the value for beedo_element.css_query
     *
     * @mbg.generated
     */
    public void setCssQuery(String cssQuery) {
        this.cssQuery = cssQuery == null ? null : cssQuery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_element.data_type
     *
     * @return the value of beedo_element.data_type
     *
     * @mbg.generated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_element.data_type
     *
     * @param dataType the value for beedo_element.data_type
     *
     * @mbg.generated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_element.document_id
     *
     * @return the value of beedo_element.document_id
     *
     * @mbg.generated
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_element.document_id
     *
     * @param documentId the value for beedo_element.document_id
     *
     * @mbg.generated
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_element.gmt_create
     *
     * @return the value of beedo_element.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_element.gmt_create
     *
     * @param gmtCreate the value for beedo_element.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_element.gmt_modified
     *
     * @return the value of beedo_element.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_element.gmt_modified
     *
     * @param gmtModified the value for beedo_element.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_element.memo
     *
     * @return the value of beedo_element.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_element.memo
     *
     * @param memo the value for beedo_element.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_element.structure_type
     *
     * @return the value of beedo_element.structure_type
     *
     * @mbg.generated
     */
    public String getStructureType() {
        return structureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_element.structure_type
     *
     * @param structureType the value for beedo_element.structure_type
     *
     * @mbg.generated
     */
    public void setStructureType(String structureType) {
        this.structureType = structureType == null ? null : structureType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_element.status
     *
     * @return the value of beedo_element.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_element.status
     *
     * @param status the value for beedo_element.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}