package com.seagull.beedo.dao.domain;



import com.seagull.beedo.common.ToString;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table beedo_document
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BeedoDocument extends ToString {
    private static final long serialVersionUID = -6736554270263604933L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_document.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_document.gmt_create
     *
     * @mbg.generated
     */
    private Date    gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_document.gmt_modified
     *
     * @mbg.generated
     */
    private Date    gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_document.name
     *
     * @mbg.generated
     */
    private String  name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_document.protocol
     *
     * @mbg.generated
     */
    private String  protocol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_document.url
     *
     * @mbg.generated
     */
    private String  url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beedo_document.status
     *
     * @mbg.generated
     */
    private String  status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_document.id
     *
     * @return the value of beedo_document.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_document.id
     *
     * @param id the value for beedo_document.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_document.gmt_create
     *
     * @return the value of beedo_document.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_document.gmt_create
     *
     * @param gmtCreate the value for beedo_document.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_document.gmt_modified
     *
     * @return the value of beedo_document.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_document.gmt_modified
     *
     * @param gmtModified the value for beedo_document.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_document.name
     *
     * @return the value of beedo_document.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_document.name
     *
     * @param name the value for beedo_document.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_document.protocol
     *
     * @return the value of beedo_document.protocol
     *
     * @mbg.generated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_document.protocol
     *
     * @param protocol the value for beedo_document.protocol
     *
     * @mbg.generated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_document.url
     *
     * @return the value of beedo_document.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_document.url
     *
     * @param url the value for beedo_document.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beedo_document.status
     *
     * @return the value of beedo_document.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beedo_document.status
     *
     * @param status the value for beedo_document.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}